apiVersion : apps/v1
kind: Deployment
metadata:
  name: nawatnimbusbackend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nawatnimbusbackend
  template:
    metadata:
      labels:
        app: nawatnimbusbackend 
    spec:
      containers:
        - name: nawatnimbusbackend 
          image: nimbusacr.azurecr.io/nawatnimbusbackend
          ports:
          - containerPort: 8080
    env:
      - name: DB_URL
        valueFrom:
          secretKeyRef:
            name: nimbus-secret
            key: DB_URL
      - name: secret
        valueFrom:
          secretKeyRef:
            name: nimbus-secret
            key: secret
      - name: AZURE_STORAGE_ACCOUNT_NAME
        valueFrom:
          secretKeyRef:
            name: nimbus-secret
            key: AZURE_STORAGE_ACCOUNT_NAME
      - name: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: nimbus-secret
            key: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      